- name: Expense Frontend Setup
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx Web Server
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: copy Expense Config file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
    - name: Clean old Nginx Directory
      ansible.builtin.file:
        state: absent
        path: /usr/share/nginx/html/*
    - name: Download and Extract Frontend Content
      ansible.builtin.unarchive:
        src: http://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: Start nginx Service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes


